### ISSUE TITLE
[PE-D][Tester B] Team does not reflect after deleting contact belonging to team

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T12-1/tp#136] opened 2024-04-05 19:39 UTC
![image.png](https://raw.githubusercontent.com/howen02/ped/main/files/4092a11d-238e-4992-b8f3-5c6ebdbd04d8.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: howen02/ped#8

**Comment by angsongyee** [comment] 2024-04-08 13:57
Duplicate of #135

**Closed** 2024-04-11 12:45 UTC
