### ISSUE TITLE
[PE-D][Tester A] Editing person tag/tech stack does not update team

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T12-1/tp#132] opened 2024-04-05 19:14 UTC
![image.png](https://raw.githubusercontent.com/breezetall/ped/main/files/b6bbe5a0-ee74-492d-8e2a-e0ca8e13067c.png)

Steps to reproduce:
1) add a contact to the team
2) edit the contact by adding a tag/ts or editing a tag/ts

Calling the `team 1` also does not update this information.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: breezetall/ped#5

**Comment by angsongyee** [comment] 2024-04-08 14:27
Duplicate of #144

**Closed by angsongyee** 2024-04-08 14:27 UTC
Labels: type.Bug, severity.high
